export const MaterialUIComponentsNavigation = [{
    'id': 'appBar',
    'title': 'App Bar',
    'type': 'item',
    'url': '/documentation/material-ui-components/app-bar'
}, {
    'id': 'autocomplete',
    'title': 'Autocomplete',
    'type': 'item',
    'url': '/documentation/material-ui-components/autocomplete'
}, {
    'id': 'avatars',
    'title': 'Avatars',
    'type': 'item',
    'url': '/documentation/material-ui-components/avatars'
}, {
    'id': 'badges',
    'title': 'Badges',
    'type': 'item',
    'url': '/documentation/material-ui-components/badges'
}, {
    'id': 'bottomNavigation',
    'title': 'Bottom Navigation',
    'type': 'item',
    'url': '/documentation/material-ui-components/bottom-navigation'
}, {
    'id': 'box',
    'title': 'Box',
    'type': 'item',
    'url': '/documentation/material-ui-components/box'
}, {
    'id': 'breadcrumbs',
    'title': 'Breadcrumbs',
    'type': 'item',
    'url': '/documentation/material-ui-components/breadcrumbs'
}, {
    'id': 'buttons',
    'title': 'Buttons',
    'type': 'item',
    'url': '/documentation/material-ui-components/buttons'
}, {
    'id': 'cards',
    'title': 'Cards',
    'type': 'item',
    'url': '/documentation/material-ui-components/cards'
}, {
    'id': 'checkboxes',
    'title': 'Checkboxes',
    'type': 'item',
    'url': '/documentation/material-ui-components/checkboxes'
}, {
    'id': 'chips',
    'title': 'Chips',
    'type': 'item',
    'url': '/documentation/material-ui-components/chips'
}, {
    'id': 'clickAwayListener',
    'title': 'Click Away Listener',
    'type': 'item',
    'url': '/documentation/material-ui-components/click-away-listener'
}, {
    'id': 'container',
    'title': 'Container',
    'type': 'item',
    'url': '/documentation/material-ui-components/container'
}, {
    'id': 'cssBaseline',
    'title': 'Css Baseline',
    'type': 'item',
    'url': '/documentation/material-ui-components/css-baseline'
}, {
    'id': 'dialogs',
    'title': 'Dialogs',
    'type': 'item',
    'url': '/documentation/material-ui-components/dialogs'
}, {
    'id': 'dividers',
    'title': 'Dividers',
    'type': 'item',
    'url': '/documentation/material-ui-components/dividers'
}, {
    'id': 'drawers',
    'title': 'Drawers',
    'type': 'item',
    'url': '/documentation/material-ui-components/drawers'
}, {
    'id': 'expansionPanels',
    'title': 'Expansion Panels',
    'type': 'item',
    'url': '/documentation/material-ui-components/expansion-panels'
}, {
    'id': 'grid',
    'title': 'Grid',
    'type': 'item',
    'url': '/documentation/material-ui-components/grid'
}, {
    'id': 'gridList',
    'title': 'Grid List',
    'type': 'item',
    'url': '/documentation/material-ui-components/grid-list'
}, {
    'id': 'hidden',
    'title': 'Hidden',
    'type': 'item',
    'url': '/documentation/material-ui-components/hidden'
}, {
    'id': 'links',
    'title': 'Links',
    'type': 'item',
    'url': '/documentation/material-ui-components/links'
}, {
    'id': 'lists',
    'title': 'Lists',
    'type': 'item',
    'url': '/documentation/material-ui-components/lists'
}, {
    'id': 'menus',
    'title': 'Menus',
    'type': 'item',
    'url': '/documentation/material-ui-components/menus'
}, {
    'id': 'modal',
    'title': 'Modal',
    'type': 'item',
    'url': '/documentation/material-ui-components/modal'
}, {
    'id': 'noSsr',
    'title': 'No Ssr',
    'type': 'item',
    'url': '/documentation/material-ui-components/no-ssr'
}, {
    'id': 'paper',
    'title': 'Paper',
    'type': 'item',
    'url': '/documentation/material-ui-components/paper'
}, {
    'id': 'pickers',
    'title': 'Pickers',
    'type': 'item',
    'url': '/documentation/material-ui-components/pickers'
}, {
    'id': 'popover',
    'title': 'Popover',
    'type': 'item',
    'url': '/documentation/material-ui-components/popover'
}, {
    'id': 'popper',
    'title': 'Popper',
    'type': 'item',
    'url': '/documentation/material-ui-components/popper'
}, {
    'id': 'portal',
    'title': 'Portal',
    'type': 'item',
    'url': '/documentation/material-ui-components/portal'
}, {
    'id': 'progress',
    'title': 'Progress',
    'type': 'item',
    'url': '/documentation/material-ui-components/progress'
}, {
    'id': 'radioButtons',
    'title': 'Radio Buttons',
    'type': 'item',
    'url': '/documentation/material-ui-components/radio-buttons'
}, {
    'id': 'selects',
    'title': 'Selects',
    'type': 'item',
    'url': '/documentation/material-ui-components/selects'
}, {
    'id': 'snackbars',
    'title': 'Snackbars',
    'type': 'item',
    'url': '/documentation/material-ui-components/snackbars'
}, {
    'id': 'steppers',
    'title': 'Steppers',
    'type': 'item',
    'url': '/documentation/material-ui-components/steppers'
}, {
    'id': 'switches',
    'title': 'Switches',
    'type': 'item',
    'url': '/documentation/material-ui-components/switches'
}, {
    'id': 'tables',
    'title': 'Tables',
    'type': 'item',
    'url': '/documentation/material-ui-components/tables'
}, {
    'id': 'tabs',
    'title': 'Tabs',
    'type': 'item',
    'url': '/documentation/material-ui-components/tabs'
}, {
    'id': 'textFields',
    'title': 'Text Fields',
    'type': 'item',
    'url': '/documentation/material-ui-components/text-fields'
}, {
    'id': 'tooltips',
    'title': 'Tooltips',
    'type': 'item',
    'url': '/documentation/material-ui-components/tooltips'
}, {
    'id': 'transferList',
    'title': 'Transfer List',
    'type': 'item',
    'url': '/documentation/material-ui-components/transfer-list'
}, {
    'id': 'transitions',
    'title': 'Transitions',
    'type': 'item',
    'url': '/documentation/material-ui-components/transitions'
}, {
    'id': 'typography',
    'title': 'Typography',
    'type': 'item',
    'url': '/documentation/material-ui-components/typography'
}];